import { useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { DefinitionGrid, EmptyState, FilePicker, Icon, Modal, PageHeader, PanelHeader, StatusBadge } from '../components/ui'
import { usePlatform } from '../state/PlatformContext'

export default function BotDetailPage() {
  const { botId } = useParams()
  const navigate = useNavigate()
  const { state, toggleBot, createTask, addBotVersion, showToast } = usePlatform()
  const bot = state.bots.find((item) => item.id === botId)
  const [runOpen, setRunOpen] = useState(false)
  const [versionOpen, setVersionOpen] = useState(false)
  const [runName, setRunName] = useState('即时业务处理任务')
  const [versionForm, setVersionForm] = useState({ fileName: '', entrypoint: bot?.entrypoint || 'main.py', changeNote: '' })
  if (!bot) return <div className="page-body"><EmptyState title="Bot 不存在" description="该 Bot 可能已归档。"/></div>
  const versions = state.botVersions.filter((item) => item.bot_id === bot.id)
  const tasks = state.tasks.filter((item) => item.bot_id === bot.id)
  const schedules = state.schedules.filter((item) => item.bot_id === bot.id)
  const runBot = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const id = createTask({ botId: bot.id, name: runName, totalItems: 1 }); setRunOpen(false); if (id) navigate(`/tasks/${id}`) }
  const uploadVersion = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!versionForm.fileName || !versionForm.changeNote) { showToast('请选择脚本包并填写变更说明'); return } addBotVersion(bot.id, versionForm); setVersionOpen(false) }
  return <div className="page-body">
    <PageHeader eyebrow={bot.code} title={bot.name} description={bot.description} backTo="/bots" actions={<><StatusBadge status={bot.status}/><button className="secondary-button" onClick={() => toggleBot(bot.id)}>{bot.status === 'enabled' ? '停用 Bot' : '启用 Bot'}</button><button className="secondary-button" onClick={() => setVersionOpen(true)}><Icon name="upload" size={15}/>上传版本</button><button className="primary-button" disabled={bot.status !== 'enabled'} onClick={() => setRunOpen(true)}><Icon name="play" size={15}/>运行 Bot</button></>}/>
    <div className="detail-layout"><section className="panel detail-main"><PanelHeader kicker="Bot definition" title="定义与默认配置"/><DefinitionGrid items={[["稳定编码",bot.code],["分类",bot.category],["入口文件",bot.entrypoint],["脚本来源","上传文件"],["默认输入",bot.default_input_source],["默认配置",<code>{JSON.stringify(bot.default_config)}</code>],["运行要求",<code>{JSON.stringify(bot.default_requirements)}</code>],["创建人",bot.created_by],["最后更新",bot.updated_at]]}/><div className="tag-row detail-tags">{bot.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></section><aside className="detail-side"><section className="panel side-card"><PanelHeader kicker="Relations" title="关联资源"/><div className="relation-links"><Link to={`/tasks?bot=${bot.id}`}><span>近期任务</span><strong>{tasks.length}</strong><Icon name="chevron" size={15}/></Link><Link to="/schedules"><span>调度计划</span><strong>{schedules.length}</strong><Icon name="chevron" size={15}/></Link></div></section><section className="panel side-card"><PanelHeader kicker="Current release" title="当前版本"/><div className="current-version"><strong>{versions[0]?.version}</strong><span>{versions[0]?.source_file}</span><p>{versions[0]?.change_note}</p></div></section></aside></div>
    <section className="panel workspace-panel spaced-panel"><PanelHeader kicker="Immutable history" title="版本历史"/><div className="table-wrap"><table className="data-table"><caption className="sr-only">Bot 版本历史</caption><thead><tr><th>版本</th><th>源文件</th><th>入口</th><th>变更说明</th><th>创建人</th><th>创建时间</th></tr></thead><tbody>{versions.map((version) => <tr key={version.id}><td><strong>{version.version}</strong>{version.id === bot.current_version_id && <small className="current-label">当前</small>}</td><td>{version.source_file}</td><td><code>{version.entrypoint}</code></td><td>{version.change_note}</td><td>{version.created_by}</td><td>{version.created_at}</td></tr>)}</tbody></table></div></section>
    <section className="panel workspace-panel spaced-panel"><PanelHeader kicker="Recent executions" title="近期任务"/>{tasks.length ? <div className="simple-list">{tasks.slice(0,5).map((task) => <Link to={`/tasks/${task.id}`} key={task.id}><span><strong>{task.name}</strong><small>{task.id} · {task.created_at}</small></span><StatusBadge status={task.status}/><Icon name="chevron" size={15}/></Link>)}</div> : <EmptyState title="尚无任务" description="运行 Bot 后，新任务会出现在这里。"/>}</section>

    <Modal open={runOpen} onClose={() => setRunOpen(false)} kicker="Run bot" title={`运行 ${bot.name}`}><form className="modal-form" onSubmit={runBot}><label>任务名称<input required value={runName} onChange={(event) => setRunName(event.target.value)}/></label><div className="form-note"><Icon name="file" size={18}/><p>将使用当前版本 <strong>{versions[0]?.version}</strong> 和默认运行配置创建一个 pending 任务。</p></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setRunOpen(false)}>取消</button><button className="primary-button" type="submit"><Icon name="play" size={15}/>创建任务</button></div></form></Modal>
    <Modal open={versionOpen} onClose={() => setVersionOpen(false)} kicker="Upload only" title="上传 Bot 新版本"><form className="modal-form" onSubmit={uploadVersion}><FilePicker fileName={versionForm.fileName} accept=".zip,.py" hint="第一版仅支持上传 ZIP 或 Python 脚本，最大 50 MB" onFile={(file,error) => error ? showToast(error) : setVersionForm({ ...versionForm, fileName: file?.name || '' })}/><label>入口文件<input required value={versionForm.entrypoint} onChange={(event) => setVersionForm({ ...versionForm, entrypoint: event.target.value })}/></label><label>变更说明<textarea required rows={4} value={versionForm.changeNote} onChange={(event) => setVersionForm({ ...versionForm, changeNote: event.target.value })}/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setVersionOpen(false)}>取消</button><button className="primary-button" type="submit"><Icon name="upload" size={15}/>上传并设为当前版本</button></div></form></Modal>
  </div>
}
