import { useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { DefinitionGrid, EmptyState, FilePicker, Icon, Modal, PageHeader, PanelHeader, StatusBadge } from '../components/ui'
import { formatDateTime, formatNumber } from '../i18n/formatters'
import { usePlatform } from '../state/PlatformContext'
import { useDemoText } from '../i18n/demo'

export default function BotDetailPage() {
  const { t } = useTranslation(['bots', 'common'])
  const { botId } = useParams()
  const navigate = useNavigate()
  const { state, toggleBot, createTask, addBotVersion, showToast } = usePlatform()
  const demo = useDemoText()
  const bot = state.bots.find((item) => item.id === botId)
  const [runOpen, setRunOpen] = useState(false)
  const [versionOpen, setVersionOpen] = useState(false)
  const [runName, setRunName] = useState<string>(t('bots:defaultRunName'))
  const [versionForm, setVersionForm] = useState({ fileName: '', entrypoint: bot?.entrypoint || 'main.py', changeNote: '' })
  if (!bot) return <div className="page-body"><EmptyState title={t('bots:notFoundTitle')} description={t('bots:notFoundDescription')}/></div>
  const versions = state.botVersions.filter((item) => item.bot_id === bot.id)
  const tasks = state.tasks.filter((item) => item.bot_id === bot.id)
  const schedules = state.schedules.filter((item) => item.bot_id === bot.id)
  const runBot = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const id = createTask({ botId: bot.id, name: runName, totalItems: 1 }); setRunOpen(false); if (id) navigate(`/tasks/${id}`) }
  const uploadVersion = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!versionForm.fileName || !versionForm.changeNote) { showToast('choosePackageAndNote'); return } addBotVersion(bot.id, versionForm); setVersionOpen(false) }
  return <div className="page-body">
    <PageHeader eyebrow={bot.code} title={demo('bots', bot.id, 'name', bot.name)} description={demo('bots', bot.id, 'description', bot.description)} backTo="/bots" actions={<div className="bot-detail-actions"><StatusBadge status={bot.status}/><button className="secondary-button" onClick={() => toggleBot(bot.id)}>{bot.status === 'enabled' ? t('bots:disableBot') : t('bots:enableBot')}</button><button className="secondary-button" onClick={() => setVersionOpen(true)}><Icon name="upload" size={15}/>{t('bots:uploadVersion')}</button><button className="primary-button" disabled={bot.status !== 'enabled'} onClick={() => { setRunName(t('bots:defaultRunName')); setRunOpen(true) }}><Icon name="play" size={15}/>{t('bots:runBot')}</button></div>}/>
    <div className="detail-layout"><section className="panel detail-main"><PanelHeader kicker={t('bots:definitionKicker')} title={t('bots:definitionTitle')}/><DefinitionGrid items={[[t('bots:code'),bot.code],[t('bots:category'),demo('bots', bot.id, 'category', bot.category)],[t('bots:entrypoint'),bot.entrypoint],[t('bots:scriptSource'),t('bots:uploadedFile')],[t('bots:defaultInput'),t(`common:inputSources.${bot.default_input_source}`)],[t('bots:defaultConfiguration'),<code>{JSON.stringify(bot.default_config)}</code>],[t('bots:runtimeRequirements'),<code>{JSON.stringify(bot.default_requirements)}</code>],[t('bots:createdBy'),bot.created_by],[t('bots:lastUpdated'),formatDateTime(bot.updated_at)]]}/><div className="tag-row detail-tags">{bot.tags.map((tag, index) => <span key={tag}>{demo('bots', bot.id, `tag${index}`, tag)}</span>)}</div></section><aside className="detail-side"><section className="panel side-card"><PanelHeader kicker={t('bots:relationsKicker')} title={t('bots:relatedResources')}/><div className="relation-links"><Link to={`/tasks?bot=${bot.id}`}><span>{t('bots:recentTasks')}</span><strong>{formatNumber(tasks.length)}</strong><Icon name="chevron" size={15}/></Link><Link to="/schedules"><span>{t('bots:schedules')}</span><strong>{formatNumber(schedules.length)}</strong><Icon name="chevron" size={15}/></Link></div></section><section className="panel side-card"><PanelHeader kicker={t('bots:currentReleaseKicker')} title={t('bots:currentVersion')}/><div className="current-version"><strong>{versions[0]?.version}</strong><span>{versions[0]?.source_file}</span><p>{versions[0] ? demo('botVersions', versions[0].id, 'changeNote', versions[0].change_note) : undefined}</p></div></section></aside></div>
    <section className="panel workspace-panel spaced-panel"><PanelHeader kicker={t('bots:historyKicker')} title={t('bots:versionHistory')}/><div className="table-wrap"><table className="data-table"><caption className="sr-only">{t('bots:versionHistory')}</caption><thead><tr>{[t('bots:version'),t('bots:sourceFile'),t('bots:entry'),t('bots:changeNote'),t('bots:createdBy'),t('bots:createdAt')].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{versions.map((version) => <tr key={version.id}><td><strong>{version.version}</strong>{version.id === bot.current_version_id && <small className="current-label">{t('common:current')}</small>}</td><td>{version.source_file}</td><td><code>{version.entrypoint}</code></td><td>{demo('botVersions', version.id, 'changeNote', version.change_note)}</td><td>{version.created_by}</td><td>{formatDateTime(version.created_at)}</td></tr>)}</tbody></table></div></section>
    <section className="panel workspace-panel spaced-panel"><PanelHeader kicker={t('bots:executionsKicker')} title={t('bots:recentTasks')}/>{tasks.length ? <div className="simple-list">{tasks.slice(0,5).map((task) => <Link to={`/tasks/${task.id}`} key={task.id}><span><strong>{demo('tasks', task.id, 'name', task.name)}</strong><small>{task.id} · {formatDateTime(task.created_at)}</small></span><StatusBadge status={task.status}/><Icon name="chevron" size={15}/></Link>)}</div> : <EmptyState title={t('bots:noTasksTitle')} description={t('bots:noTasksDescription')}/>}</section>
    <Modal open={runOpen} onClose={() => setRunOpen(false)} kicker={t('bots:runKicker')} title={t('bots:runModalTitle', { name: demo('bots', bot.id, 'name', bot.name) })}><form className="modal-form" onSubmit={runBot}><label>{t('bots:taskName')}<input required value={runName} onChange={(event) => setRunName(event.target.value)}/></label><div className="form-note"><Icon name="file" size={18}/><p>{t('bots:runNote', { version: versions[0]?.version })}</p></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setRunOpen(false)}>{t('common:cancel')}</button><button className="primary-button" type="submit"><Icon name="play" size={15}/>{t('bots:createTask')}</button></div></form></Modal>
    <Modal open={versionOpen} onClose={() => setVersionOpen(false)} kicker={t('bots:uploadKicker')} title={t('bots:uploadModalTitle')}><form className="modal-form" onSubmit={uploadVersion}><FilePicker fileName={versionForm.fileName} accept=".zip,.py" hint={t('bots:uploadHint')} onFile={(file,error) => error ? showToast(error) : setVersionForm({ ...versionForm, fileName: file?.name || '' })}/><label>{t('bots:entrypoint')}<input required value={versionForm.entrypoint} onChange={(event) => setVersionForm({ ...versionForm, entrypoint: event.target.value })}/></label><label>{t('bots:changeNote')}<textarea required rows={4} value={versionForm.changeNote} onChange={(event) => setVersionForm({ ...versionForm, changeNote: event.target.value })}/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setVersionOpen(false)}>{t('common:cancel')}</button><button className="primary-button" type="submit"><Icon name="upload" size={15}/>{t('bots:uploadAndSetCurrent')}</button></div></form></Modal>
  </div>
}
