import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { Icon, PanelHeader, ProgressBar, StatusBadge, TrendChart } from '../components/ui'
import { trendByPeriod } from '../data/seedData'
import { formatNumber, formatPercent, formatTime } from '../i18n/formatters'
import { usePlatform } from '../state/PlatformContext'
import { useDemoText } from '../i18n/demo'
import type { Schedule, TaskStatus } from '../domain/types'
import type { IconName } from '../components/ui'

type TrendPeriod = keyof typeof trendByPeriod
const terminalStatusFilters: readonly TaskStatus[] = ['success', 'partial_success', 'failed', 'canceled']
export default function OverviewPage() {
  const { t } = useTranslation(['overview', 'common'])
  const { state } = usePlatform()
  const demo = useDemoText()
  const [period, setPeriod] = useState<TrendPeriod>('today')
  const [chartMode, setChartMode] = useState('chart')
  const trendValues = trendByPeriod[period]
  const peakIndex = trendValues.indexOf(Math.max(...trendValues))
  const activeTasks = state.tasks.filter((task) => ['pending', 'dispatching', 'running', 'canceling'].includes(task.status))
  const terminalTasks = state.tasks.filter((task) => ['success', 'partial_success', 'failed', 'canceled', 'timeout'].includes(task.status))
  const successRate = terminalTasks.length ? Math.round((terminalTasks.filter((task) => task.status === 'success').length / terminalTasks.length) * 1000) / 10 : 100
  const onlineWorkers = state.workers.filter((worker) => worker.status === 'online')
  const enabledBots = state.bots.filter((bot) => bot.status === 'enabled')
  const upcomingSchedules = state.schedules.filter((schedule): schedule is Schedule & { next_run_at: string } => schedule.status === 'enabled' && schedule.next_run_at !== null).sort((a, b) => a.next_run_at.localeCompare(b.next_run_at)).slice(0, 3)
  const statuses = useMemo<{ status: TaskStatus; count: number }[]>(() => terminalStatusFilters.map((status) => ({ status, count: terminalTasks.filter((task) => task.status === status).length })), [terminalTasks])
  const flowNodes: readonly [IconName, string, string][] = [['bot', t('overview:flowBot'), t('overview:enabledBots', { count: enabledBots.length })], ['tasks', t('overview:flowTask'), t('overview:activeCount', { count: activeTasks.length })], ['file', t('overview:flowTaskItem'), t('overview:sampleCount', { count: state.taskItems.length })]]
  const periods: readonly TrendPeriod[] = ['today', 'week', 'month']
  return <div className="page-body">
    <section className="page-heading"><div><p className="eyebrow">{t('overview:date')}</p><h1>{t('overview:title')}</h1><p>{t('overview:description')}</p></div><div className="period-switch" aria-label={t('overview:period')} >{periods.map((key) => <button key={key} className={period === key ? 'active' : ''} aria-pressed={period === key} onClick={() => setPeriod(key)}>{t(`overview:periods.${key}`)}</button>)}</div></section>
    <section className="metric-grid" aria-label={t('overview:metrics')}>
      <Link className="metric-card metric-primary" to="/tasks"><div className="metric-label"><span>{t('overview:platformTasks')}</span><Icon name="activity" size={19}/></div><div className="metric-value">{formatNumber(state.tasks.length)}<small>{t('overview:samples')}</small></div><div className="metric-foot positive"><Icon name="arrowUp" size={13}/><strong>{formatPercent(12.4)}</strong><span>{t('overview:todayIncrease')}</span></div></Link>
      <Link className="metric-card" to="/tasks?status=success"><div className="metric-label"><span>{t('overview:successRate')}</span><Icon name="check" size={19}/></div><div className="metric-value">{formatPercent(successRate)}</div><div className="metric-foot positive"><strong>{formatNumber(terminalTasks.length)}</strong><span>{t('overview:completedTasks')}</span></div></Link>
      <Link className="metric-card" to="/tasks?active=1"><div className="metric-label"><span>{t('overview:activeTasks')}</span><Icon name="pulse" size={19}/></div><div className="metric-value">{formatNumber(activeTasks.length)}<small>{t('overview:items')}</small></div><div className="metric-foot neutral"><i/><strong>{formatNumber(enabledBots.length)}</strong><span>{t('overview:enabledBotsLabel')}</span></div></Link>
      <Link className="metric-card" to="/workers"><div className="metric-label"><span>{t('overview:workersOnline')}</span><Icon name="worker" size={19}/></div><div className="metric-value">{formatNumber(onlineWorkers.length)}<small>/ {formatNumber(state.workers.length)}</small></div><div className="metric-foot positive"><strong>{formatNumber(onlineWorkers.reduce((sum, worker) => sum + worker.free_slots, 0))}</strong><span>{t('overview:freeSlots')}</span></div></Link>
    </section>
    <section className="dashboard-grid">
      <article className="panel trend-panel"><PanelHeader kicker={t('overview:executionVolume')} title={t('overview:taskTrend')} action={<div className="view-switch"><button className={chartMode === 'chart' ? 'active' : ''} onClick={() => setChartMode('chart')}>{t('overview:chart')}</button><button className={chartMode === 'table' ? 'active' : ''} onClick={() => setChartMode('table')}>{t('overview:data')}</button></div>}/><div className="trend-summary"><strong>{formatNumber(trendValues.reduce((sum, value) => sum + value, 0))}</strong><span>{t('overview:executions')}</span><em>{t('overview:peakAt', { time: `${peakIndex + 8}:00` })}</em></div>{chartMode === 'chart' ? <TrendChart values={trendValues}/> : <div className="chart-table-wrap"><table className="chart-table"><caption className="sr-only">{t('overview:taskTrendData')}</caption><thead><tr><th>{t('overview:periodHeader')}</th><th>{t('overview:executionCount')}</th></tr></thead><tbody>{trendValues.map((value, index) => <tr key={index}><td>{index + 8}:00</td><td>{formatNumber(value)}</td></tr>)}</tbody></table></div>}<div className="chart-note"><span className="legend-line"/>{t('overview:executionCount')} <small>{t('common:demoData')}</small></div></article>
      <article className="panel flow-panel"><PanelHeader kicker={t('overview:flowKicker')} title={t('overview:flowTitle')} action={<span className="live-label"><i/>{t('overview:live')}</span>}/><div className="flow-map"><div className="flow-line"><span className="flow-signal"/></div>{flowNodes.map(([icon,title,sub], index) => <div className={`flow-node ${index === 1 ? 'active' : ''}`} key={title}><span className="node-icon"><Icon name={icon}/></span><div><strong>{title}</strong><small>{sub}</small></div><b>{[t('overview:flowStages.0'), t('overview:flowStages.1'), t('overview:flowStages.2')][index]}</b></div>)}</div><div className="worker-strip"><div><span className="server-icon"><Icon name="worker" size={18}/></span><span><strong>{t('overview:workerPool')}</strong><small>{t('overview:onlineOfTotal', { online: formatNumber(onlineWorkers.length), total: formatNumber(state.workers.length) })}</small></span></div><div className="worker-bars">{onlineWorkers.map((worker) => <span key={worker.id} style={{ height: `${worker.metrics.cpu}%` }}/>)}</div><strong>{formatPercent(Math.round(onlineWorkers.reduce((sum, worker) => sum + worker.metrics.cpu, 0) / Math.max(onlineWorkers.length, 1)))}<small>{t('overview:averageLoad')}</small></strong></div></article>
      <article className="panel status-panel"><PanelHeader kicker={t('overview:completionKicker')} title={t('overview:statusDistribution')} action={<Link className="text-button" to="/tasks">{t('common:viewAll')} <Icon name="chevron" size={14}/></Link>}/><div className="status-total"><strong>{formatNumber(terminalTasks.length)}</strong><span>{t('overview:completedTasks')}</span></div><div className="status-stack" aria-label={t('overview:statusDistribution')}>{statuses.map((item) => <span key={item.status} className={`stack-${item.status === 'success' ? 'success' : item.status === 'partial_success' ? 'warning' : item.status === 'failed' ? 'danger' : 'muted'}`} style={{ width: `${terminalTasks.length ? item.count / terminalTasks.length * 100 : 0}%` }}/>)}</div><div className="status-legend">{statuses.map((item) => <div key={item.status}><i className={`legend-${item.status === 'success' ? 'success' : item.status === 'partial_success' ? 'warning' : item.status === 'failed' ? 'danger' : 'muted'}`}/><span><StatusBadge status={item.status}/></span><strong>{formatNumber(item.count)}</strong><em>{formatPercent(terminalTasks.length ? item.count / terminalTasks.length * 100 : 0)}</em></div>)}</div></article>
      <article className="panel schedule-panel"><PanelHeader kicker={t('overview:futurePlans')} title={t('overview:schedules')} action={<Link className="icon-button small" to="/schedules" aria-label={t('overview:manageSchedules')}><Icon name="more" size={18}/></Link>}/><div className="schedule-list">{upcomingSchedules.map((schedule, index) => <Link className="schedule-row" to={`/schedules/${schedule.id}`} key={schedule.id}><time>{formatTime(schedule.next_run_at)}</time><span className="schedule-marker"><i className={index === 0 ? 'next' : ''}/></span><div><strong>{demo('schedules', schedule.id, 'name', schedule.name)}</strong><small>{schedule.cron} · {schedule.timezone}</small></div><em>{index === 0 ? t('overview:upcoming') : t('common:statuses.pending')}</em></Link>)}</div><Link className="schedule-action" to="/schedules">{t('overview:manageSchedules')} <Icon name="chevron" size={14}/></Link></article>
    </section>
    <section className="panel compact-task-panel"><PanelHeader kicker={t('overview:realtimeTasks')} title={t('overview:recentExecutions')} action={<Link className="text-button" to="/tasks">{t('overview:openTasks')} <Icon name="chevron" size={14}/></Link>}/><div className="compact-task-list">{state.tasks.slice(0, 4).map((task) => <Link to={`/tasks/${task.id}`} key={task.id}><span><strong>{demo('tasks', task.id, 'name', task.name)}</strong><small>{task.id} · {demo('bots', task.bot_id, 'name', task.bot_snapshot.name)}</small></span><StatusBadge status={task.status}/><ProgressBar value={task.statistics.progress_rate} status={task.status}/><time>{formatTime(task.created_at)}</time></Link>)}</div></section>
    <section className="lower-grid"><article className="panel bot-panel"><PanelHeader kicker={t('overview:capabilitiesKicker')} title={t('overview:botOverview')} action={<Link className="text-button" to="/bots">{t('overview:manageBots')} <Icon name="chevron" size={14}/></Link>}/><div className="bot-list">{state.bots.map((bot) => <Link className="bot-row" to={`/bots/${bot.id}`} key={bot.id}><span className="bot-glyph blue"><Icon name="bot" size={18}/></span><span><strong>{demo('bots', bot.id, 'name', bot.name)}</strong><small>{demo('bots', bot.id, 'category', bot.category)} · {bot.code}</small></span><span className="bot-success"><small>{t('overview:linkedTasks')}</small><strong>{formatNumber(state.tasks.filter((task) => task.bot_id === bot.id).length)}</strong></span><StatusBadge status={bot.status}/><Icon name="chevron" size={15}/></Link>)}</div></article><article className="insight-card"><div className="insight-top"><span><Icon name="activity" size={18}/></span><p>{t('overview:insight')}</p></div><h2>{t('overview:insightTitle')}</h2><p>{t('overview:insightDescription')}</p><div className="insight-number"><span><strong>{formatPercent(18.4)}</strong><small>{t('overview:weeklyVolume')}</small></span><div>{[35,48,44,60,68,78,92].map((height) => <i key={height} style={{height:`${height}%`}}/>)}</div></div><Link to="/results">{t('overview:viewResults')} <Icon name="chevron" size={14}/></Link></article></section>
  </div>
}
