import { useMemo, useState, type KeyboardEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { DefinitionGrid, EmptyState, Icon, PageHeader, PanelHeader, ProgressBar, StatusBadge } from '../components/ui'
import type { LogLevel, TaskLog } from '../domain/types'
import { formatDateTime, formatDuration, formatFileSize, formatNumber, formatPercent, formatTime } from '../i18n/formatters'
import { taskCanCancel, taskCanRetry, usePlatform } from '../state/PlatformContext'
import { useDemoText } from '../i18n/demo'

const tabs = ['overview', 'items', 'logs', 'results', 'artifacts', 'events'] as const
const itemStatuses = ['pending', 'running', 'success', 'failed', 'timeout', 'canceled'] as const

export default function TaskDetailPage() {
  const { t } = useTranslation(['tasks', 'common'])
  const { taskId } = useParams()
  const navigate = useNavigate()
  const { state, cancelTask, retryTask, downloadArtifact, showToast } = usePlatform()
  const demo = useDemoText()
  const [tab, setTab] = useState('overview')
  const [itemStatus, setItemStatus] = useState('all')
  const [logLevel, setLogLevel] = useState<LogLevel | 'all'>('all')
  const [extraLogs, setExtraLogs] = useState<TaskLog[]>([])
  const task = state.tasks.find((item) => item.id === taskId)
  const bot = state.bots.find((item) => item.id === task?.bot_id)
  const worker = state.workers.find((item) => item.id === task?.worker_id)
  const items = state.taskItems.filter((item) => item.task_id === taskId && (itemStatus === 'all' || item.status === itemStatus))
  const logs = useMemo(() => [...extraLogs, ...state.logs.filter((item) => item.task_id === taskId)].filter((item) => logLevel === 'all' || item.level === logLevel).sort((a,b) => a.seq - b.seq), [extraLogs, state.logs, taskId, logLevel])
  const results = state.results.filter((item) => item.task_id === taskId)
  const artifacts = state.artifacts.filter((item) => item.task_id === taskId)
  const events = state.taskEvents.filter((item) => item.task_id === taskId)

  if (!task) return <div className="page-body"><EmptyState title={t('tasks:notFound.title')} description={t('tasks:notFound.description')}/></div>

  const retry = (mode: 'all' | 'failed_items'): void => { const id = retryTask(task.id, mode); if (id) navigate(`/tasks/${id}`) }
  const appendDemoLog = () => {
    const number = extraLogs.length + 1
    setExtraLogs((current) => [...current, { id: `LOCAL-${number}`, task_id: task.id, task_item_id: null, level: number % 3 === 0 ? 'warning' : 'info', source: 'script', seq: 100 + number, message: number % 3 === 0 ? '检测到一条业务校验警告，继续执行' : `实时日志事件 ${number} 已写入`, created_at: `10:48:${String(number * 3).padStart(2,'0')}` }])
    showToast('sseSimulated')
  }
  const handleTabKey = (event: KeyboardEvent<HTMLButtonElement>, index: number): void => {
    if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return
    event.preventDefault()
    const nextIndex = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : (index + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length
    setTab(tabs[nextIndex])
    document.getElementById(`task-tab-${tabs[nextIndex]}`)?.focus()
  }

  return <div className="page-body">
    <PageHeader eyebrow={task.id} title={demo('tasks', task.id, 'name', task.name)} description={`${demo('bots', task.bot_id, 'name', task.bot_snapshot.name)} · ${demo('tasks', task.id, 'owner', task.owner)}`} backTo="/tasks" actions={<><StatusBadge status={task.status}/>{taskCanCancel(task) && <button className="secondary-button danger-button" onClick={() => cancelTask(task.id)}><Icon name="close" size={15}/>{t('tasks:actions.cancel')}</button>}{taskCanRetry(task) && <><button className="secondary-button" onClick={() => retry('failed_items')}><Icon name="refresh" size={15}/>{t('common:runTypes.retry_failed_items')}</button><button className="primary-button" onClick={() => retry('all')}><Icon name="refresh" size={15}/>{t('common:runTypes.retry_all')}</button></>}</>}/>

    <nav className="detail-tabs" aria-label={t('tasks:detail.tabsAriaLabel')} role="tablist">{tabs.map((key, index) => <button key={key} id={`task-tab-${key}`} role="tab" tabIndex={tab === key ? 0 : -1} className={tab === key ? 'active' : ''} aria-selected={tab === key} aria-controls={`task-panel-${key}`} onKeyDown={(event) => handleTabKey(event, index)} onClick={() => setTab(key)}>{t(`tasks:tabs.${key}`)}{key === 'items' ? ` ${formatNumber(state.taskItems.filter((item) => item.task_id === task.id).length)}` : key === 'results' ? ` ${formatNumber(results.length)}` : key === 'artifacts' ? ` ${formatNumber(artifacts.length)}` : ''}</button>)}</nav>

    {tab === 'overview' && <div className="detail-layout" role="tabpanel" id="task-panel-overview" aria-labelledby="task-tab-overview">
      <section className="panel detail-main"><PanelHeader kicker={t('tasks:overview.kicker')} title={t('tasks:overview.title')}/><div className="task-hero-progress"><ProgressBar value={task.statistics.progress_rate} status={task.status}/><div><strong>{formatNumber(task.statistics.completed_items)}</strong><span>{t('tasks:overview.completedSummary', { total: formatNumber(task.statistics.total_items) })}</span></div></div><div className="stat-strip">{([{ key: 'success', label: t('tasks:overview.stats.success'), value: task.statistics.success_items }, { key: 'failed', label: t('tasks:overview.stats.failed'), value: task.statistics.failed_items }, { key: 'timeout', label: t('tasks:overview.stats.timeout'), value: task.statistics.timeout_items }, { key: 'results', label: t('tasks:overview.stats.results'), value: task.statistics.total_results }, { key: 'artifacts', label: t('tasks:overview.stats.artifacts'), value: task.statistics.artifact_count }, { key: 'errorLogs', label: t('tasks:overview.stats.errorLogs'), value: task.statistics.error_log_count }]).map((item) => <div key={item.key}><span>{item.label}</span><strong>{formatNumber(item.value)}</strong></div>)}</div>{task.error_message && <div className="error-callout"><Icon name="activity" size={18}/><div><strong>{task.error_code}</strong><p>{demo('tasks', task.id, 'errorMessage', task.error_message)}</p></div></div>}<DefinitionGrid items={[[t('tasks:overview.details.inputSource'), t(`common:inputSources.${task.input_source}`)], [t('tasks:overview.details.inputSummary'), task.input_summary], [t('tasks:overview.details.runType'), t(`common:runTypes.${task.run_type}`)], [t('tasks:overview.details.priority'), t(`common:priorities.${task.priority}`)], [t('tasks:overview.details.createdAt'), formatDateTime(task.created_at)], [t('tasks:overview.details.startedAt'), formatDateTime(task.started_at)], [t('tasks:overview.details.finishedAt'), formatDateTime(task.finished_at)]]}/></section>
      <aside className="detail-side"><section className="panel side-card"><PanelHeader kicker={t('tasks:overview.snapshot.kicker')} title={t('tasks:overview.snapshot.title')}/><DefinitionGrid items={[[t('tasks:overview.snapshot.bot'), bot ? <Link to={`/bots/${bot.id}`}>{demo('bots', task.bot_id, 'name', task.bot_snapshot.name)}</Link> : demo('bots', task.bot_id, 'name', task.bot_snapshot.name)], [t('tasks:overview.snapshot.version'), task.bot_snapshot.version], [t('tasks:overview.snapshot.entrypoint'), task.bot_snapshot.entrypoint], [t('tasks:overview.snapshot.sourceTask'), task.source_task_id ? <Link to={`/tasks/${task.source_task_id}`}>{task.source_task_id}</Link> : t('common:none')], [t('tasks:overview.snapshot.schedule'), task.schedule_id ? <Link to={`/schedules/${task.schedule_id}`}>{task.schedule_id}</Link> : t('common:runTypes.manual')]]}/></section><section className="panel side-card"><PanelHeader kicker={t('tasks:overview.worker.kicker')} title={t('tasks:overview.worker.title')}/>{worker ? <><Link className="worker-link-card" to={`/workers/${worker.id}`}><span className={`health-indicator ${worker.status}`}/><div><strong>{demo('workers', worker.id, 'name', worker.name)}</strong><small>{worker.hostname}</small></div><Icon name="chevron" size={15}/></Link><DefinitionGrid items={[[t('tasks:overview.worker.cpu'), formatPercent(worker.metrics.cpu)], [t('tasks:overview.worker.memory'), formatPercent(worker.metrics.memory)], [t('tasks:overview.worker.slots'), t('tasks:overview.worker.slotsValue', { current: formatNumber(worker.current_running), max: formatNumber(worker.max_concurrency) })], [t('tasks:overview.worker.lastHeartbeat'), formatDateTime(worker.last_heartbeat_at)]]}/></> : <p className="muted-copy">{t('tasks:overview.worker.awaitingAssignment')}</p>}</section></aside>
    </div>}

    {tab === 'items' && <section className="panel workspace-panel" role="tabpanel" id="task-panel-items" aria-labelledby="task-tab-items"><div className="workspace-toolbar"><div><p className="panel-kicker">{t('tasks:items.kicker')}</p><h2>{t('tasks:tabs.items')}</h2></div><select aria-label={t('tasks:items.statusFilterAriaLabel')} value={itemStatus} onChange={(event) => setItemStatus(event.target.value)}><option value="all">{t('tasks:items.allStatuses')}</option>{itemStatuses.map((itemStatus) => <option key={itemStatus} value={itemStatus}>{t(`common:statuses.${itemStatus}`)}</option>)}</select></div><div className="table-wrap"><table className="data-table"><caption className="sr-only">{t('tasks:items.table.caption')}</caption><thead><tr><th>{t('tasks:items.table.indexKey')}</th><th>{t('tasks:items.table.type')}</th><th>{t('tasks:items.table.status')}</th><th>{t('tasks:items.table.summary')}</th><th>{t('tasks:items.table.duration')}</th><th>{t('tasks:items.table.relatedData')}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>#{formatNumber(item.index)} · {item.key}</strong><small>{item.id}</small></td><td>{t(`common:itemTypes.${item.type}`)}</td><td><StatusBadge status={item.status}/></td><td><strong>{demo('taskItems', item.id, 'summary', item.summary)}</strong>{item.error_message && <small className="error-text">{demo('taskItems', item.id, 'errorMessage', item.error_message)}</small>}<details><summary>{t('tasks:items.viewInputOutput')}</summary><p>{t('tasks:items.input', { value: item.input_data })}</p><p>{t('tasks:items.output', { value: item.output_data || t('common:none') })}</p></details></td><td>{item.duration_ms !== null ? formatDuration(item.duration_ms) : t('common:statuses.running')}</td><td>{t('tasks:items.relatedDataSummary', { results: formatNumber(item.result_count), artifacts: formatNumber(item.artifact_count), logs: formatNumber(item.log_count) })}</td></tr>)}</tbody></table></div>{!items.length && <EmptyState title={t('tasks:items.empty.title')} description={t('tasks:items.empty.description')}/>}</section>}

    {tab === 'logs' && <section className="panel log-panel" role="tabpanel" id="task-panel-logs" aria-labelledby="task-tab-logs"><div className="workspace-toolbar"><div><p className="panel-kicker">{t('tasks:logs.kicker')}</p><h2>{t('tasks:tabs.logs')}</h2></div><div className="toolbar-actions"><select aria-label={t('tasks:logs.levelFilterAriaLabel')} value={logLevel} onChange={(event) => { const next = event.target.value; if (next === 'all' || next === 'info' || next === 'warning' || next === 'error') setLogLevel(next) }}><option value="all">{t('tasks:logs.allLevels')}</option>{(['info', 'warning', 'error'] as const).map((level) => <option key={level} value={level}>{t(`common:logLevels.${level}`)}</option>)}</select>{['running', 'dispatching'].includes(task.status) && <button className="secondary-button" onClick={appendDemoLog}><Icon name="pulse" size={15}/>{t('tasks:logs.simulateEvent')}</button>}</div></div><div className="log-console" aria-live="polite">{logs.map((log) => <div key={log.id} className={`log-line log-${log.level}`}><time>{formatTime(log.created_at)}</time><b>{t(`common:logLevels.${log.level}`)}</b><span>{t(`common:logSources.${log.source}`)}</span><p>{log.message}</p>{log.task_item_id && <button aria-label={t('tasks:logs.viewItem', { id: log.task_item_id })} onClick={() => { setItemStatus('all'); setTab('items') }}>{log.task_item_id}</button>}</div>)}</div>{!logs.length && <EmptyState title={t('tasks:logs.empty.title')} description={t('tasks:logs.empty.description')}/>}</section>}

    {tab === 'results' && <section className="panel workspace-panel" role="tabpanel" id="task-panel-results" aria-labelledby="task-tab-results"><PanelHeader kicker={t('tasks:results.kicker')} title={t('tasks:tabs.results')}/>{results.length ? <div className="result-grid">{results.map((result) => <article key={result.id} className="result-card"><div><StatusBadge status="success"/><code>{t(`common:resultTypes.${result.type}`)}</code></div><h3>{result.key}</h3><pre>{JSON.stringify(result.data, null, 2)}</pre><small>{result.id} · {result.task_item_id || t('tasks:results.taskLevel')}</small></article>)}</div> : <EmptyState icon="database" title={t('tasks:results.empty.title')} description={t('tasks:results.empty.description')}/>}</section>}

    {tab === 'artifacts' && <section className="panel workspace-panel" role="tabpanel" id="task-panel-artifacts" aria-labelledby="task-tab-artifacts"><PanelHeader kicker={t('tasks:artifacts.kicker')} title={t('tasks:tabs.artifacts')}/>{artifacts.length ? <div className="artifact-list">{artifacts.map((artifact) => <article key={artifact.id}><span className="artifact-icon"><Icon name="file" size={20}/></span><div><strong>{artifact.name}</strong><small>{t(`common:artifactTypes.${artifact.type}`)} · {artifact.content_type} · {formatFileSize(artifact.size)}</small></div><code>{artifact.checksum}</code><button className="secondary-button" onClick={() => downloadArtifact(artifact)}><Icon name="download" size={15}/>{t('common:download')}</button></article>)}</div> : <EmptyState icon="file" title={t('tasks:artifacts.empty.title')} description={t('tasks:artifacts.empty.description')}/>}</section>}

    {tab === 'events' && <section className="panel event-panel" role="tabpanel" id="task-panel-events" aria-labelledby="task-tab-events"><PanelHeader kicker={t('tasks:events.kicker')} title={t('tasks:tabs.events')}/><ol className="event-timeline">{events.map((event) => <li key={event.id}><span/><time>{formatDateTime(event.at)}</time><div><strong>{event.label}</strong><small>{event.actor}</small></div></li>)}</ol>{!events.length && <EmptyState title={t('tasks:events.empty.title')} description={t('tasks:events.empty.description')}/>}</section>}
  </div>
}
